name: CI Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Run CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.23.0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.13.1
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck Code
        run: pnpm --filter @aws/cloudkit typecheck

      - name: Lint Code
        run: pnpm lint

      - name: Lint Fix
        run: pnpm lint:fix

      - name: Format Code
        run: pnpm format

      - name: Check Formatting
        run: pnpm format:check

      - name: Run Tests
        run: pnpm --filter @aws/cloudkit test/unit

      - name: Build with Tsup
        run: pnpm --filter @aws/cloudkit build